### ISSUE TITLE
Useless permission definition in manifest file

### ISSUE THREAD

**Issue by golubov-csaba-antal** [infobip/mobile-messaging-sdk-android#1]
Why do you need to define the following permission in the manifest file?

`    <permission
        android:name=".permission.C2D_MESSAGE"
        android:protectionLevel="signature" />`

It misses the ${applicationId}. Thus I can not compile the app because it generates the following error:

/src/main/AndroidManifest.xml Error:
	Attribute permission#com.miomni.JerrysNugget.permission.C2D_MESSAGE@name value=(.permission.C2D_MESSAGE) from (unknown)
	is also present at [com.google.firebase:firebase-iid:11.4.2] AndroidManifest.xml:24:17-71 value=(com.miomni.JerrysNugget.permission.C2D_MESSAGE).
	Suggestion: add 'tools:replace="android:name"' to <permission> element at AndroidManifest.xml:17:5-19:47 to override.

**Comment by stanislavin** [comment]
@CsabaZz we are keeping this permission because different people use different combinations of our library and google services. I was unable to reproduce your issue with merger & firebase-iid 11.4.2, so I just added ${applicationId} and released 1.8.5.

If it will not help - please provide your gradle dependencies, android studio version, compile sdk version and if you're adding any permissions in app's manfiest.

**Comment by golubov-csaba-antal** [comment]
It was helped me to copy both the permission and uses-permission entries just like they are in the lib's manifest, and put the tools:node="remove" attribute to both. Frankly, I have no idea whether this could have side-effect.

I'll give a try to v1.8.5 as soon as I get home today, my macbook's battery almost runs out. :)

**Comment by golubov-csaba-antal** [comment]
The v1.8.4 is still broken for me with Android Studio 3.0 and targeting to API 27 (the build tools version is 27.0.0 as well).

However, the v1.8.5 **works**! So thank you for the quick answer and fix. I'll close this task.
