### ISSUE TITLE
How to change Notification title?

### ISSUE THREAD

**Issue by hpatel123** [infobip/mobile-messaging-sdk-android#15]
Team, we are using infobip sdk and to customise push notification configuration we have used couple of methods, for example  `withDefaultIcon`, `withColor` but our requirement is to change the title of the push notification. We've tried `.withDefaultTitle(getString(R.string.title_push_notification))` but unfortunately it doesn't work.

Can you please provide your inputs for the same ?

**Comment by tjuric** [comment]
Hi @hpatel123,

can you tell us OS version, SDK version and which device did you use for testing. 
This is the preview of notification and title displayed on device with API 28: 
<img width="302" alt="Screenshot 2019-09-17 at 09 54 49" src="https://user-images.githubusercontent.com/2648565/65022507-6903ea80-d931-11e9-9928-9387acc5b6e6.png">

Method `.withDefaultTitle(getString(R.string.title_push_notification))` should display the provided title as shown above. If you don't send `title` within push notification, then default title should be displayed.

Default notification title might be overridden with title provided over [API](https://dev.infobip.com/push-messaging/send-single-push-notification#notification-options) or [web portal](https://portal.infobip.com/communications/broadcast/).

Regards,
Tereza

**Comment by hpatel123** [comment]
Hi @tjuric thanks for the update.

Device name: Pixel XL
OS: Android Q
Android version: 10
SDK version: 2.1.1@aar

We want to customise the App name here. PFA. Please check the blue coloured box.

Do let us know if there is anyway to achieve this.

<img width="302" alt="65022507-6903ea80-d931-11e9-9928-9387acc5b6e6" src="https://user-images.githubusercontent.com/6604701/65023707-04f11e80-d951-11e9-8ffc-fd082773af06.png">

**Comment by tjuric** [comment]
This is a parameter that is by default notification builder displayed as the application name for users to know which app did they receive push from. 
It’s advisable to leave it so and not change it since your end users would probably like to know which app did they receive push from. Notification builder doesn’t allow us to modify this name on default notification view. 

Subtext might be changed. This is a subtext:
![subtext](https://user-images.githubusercontent.com/2648565/65027062-f9dec400-d939-11e9-89a3-501843cf8438.png)

If you'd like to, you might play with notification collapsed and extended view design on your own. For this case you'd need to use `withoutDisplayNotification()` method:
```
new MobileMessaging.Builder(application)
            .withoutDisplayNotification()
            .build();
```
listen for [`MESSAGE_RECEIVED`](https://github.com/infobip/mobile-messaging-sdk-android/wiki/Events#message_received) event and display notifications in `onReceive` method for that action. 

You'd need to use custom notification views - RemoteView. Check up [this article](https://developer.android.com/training/notify-user/custom-notification).

**Comment by hpatel123** [comment]
Alright @tjuric . Thanks for the detailed answer.

**Comment by tjuric** [comment]
Closing this thread since we've provided all the required feedback. 
Please, reopen it if you have any other inputs abut the topic.
