### ISSUE TITLE
Silent message displays notification

### ISSUE THREAD

**Issue by p1nkydev** [infobip/mobile-messaging-sdk-android#31]
The `InAppChatImpl` ignores Message's property `isSilent` in the `handleMessage` method. That's why notification is being displayed for silent messages.

**Comment by tjuric** [comment]
Hi @p1nkydev,
Live Chat (or [In-app chat](https://github.com/infobip/mobile-messaging-sdk-android/wiki/In%E2%80%90app-chat)) is a feature that comes with dedicated type of push notifications that don't deal with "silent" property since In-app chat messages are sent internally by our platform to our SDK and we always send them as non-silent.

They serve the purpose of alarming users of the new incoming chat message. 

Did you experience any issues with this? I might accept your PR, but I'm positive about that flag never being sent for in-app chat notifications (however, it's sent for regular push and geo notifications).

**Comment by p1nkydev** [comment]
Hi @tjuric, thanks for your answer!
I have really specific case of infobip integration. 
Since by click on push notification i need to open activity with specific task affinity i can't use standard Infobip's API for that. 

So i decided to display Infobip's push messages in my own custom way, but at the same time, i need to pass such messages to SDK itself (to update unread count, etc.), so i'm passing them as "silent" to not display notifications twice (my custom + from SDK)

So i get the point where silent pushes are ignored in ChatImpl somewhy.

**Comment by tjuric** [comment]
We have released SDK version [6.3.0](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/6.3.0) with your PR changes. Feel free to update it in your app.

BR,
Tereza
