### ISSUE TITLE
Remove Multidex Dependency Implementation on Android Chat SDK

### ISSUE THREAD

**Issue by DimaSkopiuk** [infobip/mobile-messaging-sdk-android#42]
Our app configured to use min Android API 26. Thus we don't need to configure Multidex additionally according to [official docs](https://developer.android.com/build/multidex#mdex-on-l).
Moreover we are using AndroidX lib versions that are incompatible with Android.Support versions.
Since Android Messaging Chat SDK v7+ implementation of `com.android.support:multidex:2.0.1` was added to [build.gradle](https://github.com/infobip/mobile-messaging-sdk-android/blob/master/infobip-mobile-messaging-android-chat-sdk/build.gradle#L102) we became incompatible with Infobip Android Messaging Chat SDK.

Your [project](https://github.com/infobip/mobile-messaging-sdk-android/tree/master/infobip-mobile-messaging-android-chat-sdk) is library. Could you remove `com.android.support:multidex:2.0.1` so it can be added to final implementations on demand only if it is needed?

Thank you.

**Comment by jakubdzubak1** [comment]
Hello @DimaSkopiuk, multidex was enabled because it is mandatory requirement for [desugaring](https://developer.android.com/studio/write/java8-support#library-desugaring). We will think about solution and deliver it in next release.

Are you going to use also our [infobip-rtc-ui](https://github.com/infobip/mobile-messaging-sdk-android/tree/master/infobip-rtc-ui) library? I am asking because there is also multidex enabled.

 Thank you for report.

**Comment by DimaSkopiuk** [comment]
No, we are using only Messaging Chat SDK for now and no plans for RTC so far.

**Comment by jakubdzubak1** [comment]
Hello @DimaSkopiuk, we just released version [11.1.0](https://github.com/infobip/mobile-messaging-sdk-android/releases/tag/11.1.0) with disabled multidex for chat module.
